[character]
# success_symbol = "[ó°•](bold green)"
# error_symbol = "[ó°•](bold red)"
# vicmd_symbol = "[ï‰½](bold green)"
success_symbol = "[ğŸˆ](#a6e3a1 bold)"
error_symbol = "[ğŸˆ](#f38ba8)"
vicmd_symbol = "[ğŸˆ](#f9e2af)"

# [directory]
# style = "blue bold"

[directory]
format = "[î‚¶]($style)[(bg:#f5c2e7 fg:#eba0ac)$path](bg:#f5c2e7 fg:#a84c8d)[î‚´ ]($style)"
style = "bg:#fafafa fg:#f5c2e7"

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[dart]
symbol = "î˜ "

[nodejs]
symbol = "â¬¢ "

[java]
symbol = "java "
